CREATE TABLE band_user_event
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   UUID,
    band_id   BIGINT                                  NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_banduserevent PRIMARY KEY (id)
);

CREATE TABLE campaign_user_event
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    timestamp   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id     UUID,
    campaign_id BIGINT,
    CONSTRAINT pk_campaignuserevent PRIMARY KEY (id)
);

CREATE TABLE campaigns
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    generated_key UUID,
    platform      VARCHAR(255),
    subgroup      VARCHAR(255),
    post_url      VARCHAR(255),
    target_url    VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_campaigns PRIMARY KEY (id)
);

CREATE TABLE users
(
    id               UUID                        NOT NULL,
    location         VARCHAR(255)                NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    referrer         VARCHAR(255),
    operating_system VARCHAR(255),
    browser          VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE venue_user_event
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   UUID,
    venue_id  BIGINT                                  NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_venueuserevent PRIMARY KEY (id)
);

CREATE TABLE video_user_event
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   UUID,
    video_id  VARCHAR(255)                            NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_videouserevent PRIMARY KEY (id)
);

ALTER TABLE band_user_event
    ADD CONSTRAINT FK_BANDUSEREVENT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE campaign_user_event
    ADD CONSTRAINT FK_CAMPAIGNUSEREVENT_ON_CAMPAIGN FOREIGN KEY (campaign_id) REFERENCES campaigns (id);

ALTER TABLE campaign_user_event
    ADD CONSTRAINT FK_CAMPAIGNUSEREVENT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE venue_user_event
    ADD CONSTRAINT FK_VENUEUSEREVENT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE video_user_event
    ADD CONSTRAINT FK_VIDEOUSEREVENT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);