CREATE TABLE band_user_event
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   BIGINT                                  NOT NULL,
    band_id   BIGINT                                  NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_banduserevent PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    location         VARCHAR(255)                            NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    referrer         VARCHAR(255),
    operating_system VARCHAR(255),
    browser          VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE venue_user_event
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   BIGINT                                  NOT NULL,
    venue_id  BIGINT                                  NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_venueuserevent PRIMARY KEY (id)
);

CREATE TABLE video_user_event
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   BIGINT                                  NOT NULL,
    video_id  BIGINT                                  NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_videouserevent PRIMARY KEY (id)
);