CREATE TABLE search_user_event
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    location_id       VARCHAR(255),
    formatted_address VARCHAR(255),
    town              VARCHAR(255),
    county            VARCHAR(255),
    timestamp         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id           UUID,
    campaign_id       BIGINT,
    CONSTRAINT pk_searchuserevent PRIMARY KEY (id)
);

ALTER TABLE search_user_event
    ADD CONSTRAINT FK_SEARCHUSEREVENT_ON_CAMPAIGN FOREIGN KEY (campaign_id) REFERENCES campaign (id);

ALTER TABLE search_user_event
    ADD CONSTRAINT FK_SEARCHUSEREVENT_ON_USER FOREIGN KEY (user_id) REFERENCES lmf_user (id);