ALTER TABLE campaign_user_event
DROP
CONSTRAINT fk_campaignuserevent_on_campaign;

ALTER TABLE campaign_user_event
DROP
CONSTRAINT fk_campaignuserevent_on_user;

CREATE TABLE session
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url_entry                 VARCHAR(255),
    session_start             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_session_activity     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    session_activity_overview TEXT,
    user_id                   UUID,
    campaign_id               BIGINT,
    CONSTRAINT pk_session PRIMARY KEY (id)
);

ALTER TABLE session
    ADD CONSTRAINT FK_SESSION_ON_CAMPAIGN FOREIGN KEY (campaign_id) REFERENCES campaign (id);

ALTER TABLE session
    ADD CONSTRAINT FK_SESSION_ON_USER FOREIGN KEY (user_id) REFERENCES lmf_user (id);

DROP TABLE campaign_user_event CASCADE;